// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/slovty/mo-gin/internal/app/controller"
	"github.com/slovty/mo-gin/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	userCtl := controller.UserCtl{}
	routerRouter := &router.Router{
		UserCtl: userCtl,
	}
	injector := &Injector{
		Router: routerRouter,
	}
	return injector, func() {
	}, nil
}
